name: Deploy
on:
  push:
    branches: [ "master" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: actions/checkout@v3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          export PATH=$PATH:/usr/local/go/bin
          cd golang-ec2/
          git pull
          go run tugas/curdusers/main.go
